// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q               = new(Query)
	Article         *article
	ArticleBookmark *articleBookmark
	ArticleLike     *articleLike
	ArticleVersion  *articleVersion
	Category        *category
	Comment         *comment
	CommentLike     *commentLike
	File            *file
	Session         *session
	User            *user
	WebInfo         *webInfo
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	Article = &Q.Article
	ArticleBookmark = &Q.ArticleBookmark
	ArticleLike = &Q.ArticleLike
	ArticleVersion = &Q.ArticleVersion
	Category = &Q.Category
	Comment = &Q.Comment
	CommentLike = &Q.CommentLike
	File = &Q.File
	Session = &Q.Session
	User = &Q.User
	WebInfo = &Q.WebInfo
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:              db,
		Article:         newArticle(db, opts...),
		ArticleBookmark: newArticleBookmark(db, opts...),
		ArticleLike:     newArticleLike(db, opts...),
		ArticleVersion:  newArticleVersion(db, opts...),
		Category:        newCategory(db, opts...),
		Comment:         newComment(db, opts...),
		CommentLike:     newCommentLike(db, opts...),
		File:            newFile(db, opts...),
		Session:         newSession(db, opts...),
		User:            newUser(db, opts...),
		WebInfo:         newWebInfo(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Article         article
	ArticleBookmark articleBookmark
	ArticleLike     articleLike
	ArticleVersion  articleVersion
	Category        category
	Comment         comment
	CommentLike     commentLike
	File            file
	Session         session
	User            user
	WebInfo         webInfo
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Article:         q.Article.clone(db),
		ArticleBookmark: q.ArticleBookmark.clone(db),
		ArticleLike:     q.ArticleLike.clone(db),
		ArticleVersion:  q.ArticleVersion.clone(db),
		Category:        q.Category.clone(db),
		Comment:         q.Comment.clone(db),
		CommentLike:     q.CommentLike.clone(db),
		File:            q.File.clone(db),
		Session:         q.Session.clone(db),
		User:            q.User.clone(db),
		WebInfo:         q.WebInfo.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:              db,
		Article:         q.Article.replaceDB(db),
		ArticleBookmark: q.ArticleBookmark.replaceDB(db),
		ArticleLike:     q.ArticleLike.replaceDB(db),
		ArticleVersion:  q.ArticleVersion.replaceDB(db),
		Category:        q.Category.replaceDB(db),
		Comment:         q.Comment.replaceDB(db),
		CommentLike:     q.CommentLike.replaceDB(db),
		File:            q.File.replaceDB(db),
		Session:         q.Session.replaceDB(db),
		User:            q.User.replaceDB(db),
		WebInfo:         q.WebInfo.replaceDB(db),
	}
}

type queryCtx struct {
	Article         IArticleDo
	ArticleBookmark IArticleBookmarkDo
	ArticleLike     IArticleLikeDo
	ArticleVersion  IArticleVersionDo
	Category        ICategoryDo
	Comment         ICommentDo
	CommentLike     ICommentLikeDo
	File            IFileDo
	Session         ISessionDo
	User            IUserDo
	WebInfo         IWebInfoDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Article:         q.Article.WithContext(ctx),
		ArticleBookmark: q.ArticleBookmark.WithContext(ctx),
		ArticleLike:     q.ArticleLike.WithContext(ctx),
		ArticleVersion:  q.ArticleVersion.WithContext(ctx),
		Category:        q.Category.WithContext(ctx),
		Comment:         q.Comment.WithContext(ctx),
		CommentLike:     q.CommentLike.WithContext(ctx),
		File:            q.File.WithContext(ctx),
		Session:         q.Session.WithContext(ctx),
		User:            q.User.WithContext(ctx),
		WebInfo:         q.WebInfo.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
