// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"blog/model_def"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newArticleBookmark(db *gorm.DB, opts ...gen.DOOption) articleBookmark {
	_articleBookmark := articleBookmark{}

	_articleBookmark.articleBookmarkDo.UseDB(db, opts...)
	_articleBookmark.articleBookmarkDo.UseModel(&model_def.ArticleBookmark{})

	tableName := _articleBookmark.articleBookmarkDo.TableName()
	_articleBookmark.ALL = field.NewAsterisk(tableName)
	_articleBookmark.ID = field.NewUint(tableName, "id")
	_articleBookmark.CreatedAt = field.NewTime(tableName, "created_at")
	_articleBookmark.UpdatedAt = field.NewTime(tableName, "updated_at")
	_articleBookmark.DeletedAt = field.NewField(tableName, "deleted_at")
	_articleBookmark.UserID = field.NewInt32(tableName, "user_id")
	_articleBookmark.ArticleID = field.NewInt32(tableName, "article_id")

	_articleBookmark.fillFieldMap()

	return _articleBookmark
}

type articleBookmark struct {
	articleBookmarkDo articleBookmarkDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	UserID    field.Int32
	ArticleID field.Int32

	fieldMap map[string]field.Expr
}

func (a articleBookmark) Table(newTableName string) *articleBookmark {
	a.articleBookmarkDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a articleBookmark) As(alias string) *articleBookmark {
	a.articleBookmarkDo.DO = *(a.articleBookmarkDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *articleBookmark) updateTableName(table string) *articleBookmark {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.UserID = field.NewInt32(table, "user_id")
	a.ArticleID = field.NewInt32(table, "article_id")

	a.fillFieldMap()

	return a
}

func (a *articleBookmark) WithContext(ctx context.Context) IArticleBookmarkDo {
	return a.articleBookmarkDo.WithContext(ctx)
}

func (a articleBookmark) TableName() string { return a.articleBookmarkDo.TableName() }

func (a articleBookmark) Alias() string { return a.articleBookmarkDo.Alias() }

func (a articleBookmark) Columns(cols ...field.Expr) gen.Columns {
	return a.articleBookmarkDo.Columns(cols...)
}

func (a *articleBookmark) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *articleBookmark) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 6)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["article_id"] = a.ArticleID
}

func (a articleBookmark) clone(db *gorm.DB) articleBookmark {
	a.articleBookmarkDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a articleBookmark) replaceDB(db *gorm.DB) articleBookmark {
	a.articleBookmarkDo.ReplaceDB(db)
	return a
}

type articleBookmarkDo struct{ gen.DO }

type IArticleBookmarkDo interface {
	gen.SubQuery
	Debug() IArticleBookmarkDo
	WithContext(ctx context.Context) IArticleBookmarkDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IArticleBookmarkDo
	WriteDB() IArticleBookmarkDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IArticleBookmarkDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IArticleBookmarkDo
	Not(conds ...gen.Condition) IArticleBookmarkDo
	Or(conds ...gen.Condition) IArticleBookmarkDo
	Select(conds ...field.Expr) IArticleBookmarkDo
	Where(conds ...gen.Condition) IArticleBookmarkDo
	Order(conds ...field.Expr) IArticleBookmarkDo
	Distinct(cols ...field.Expr) IArticleBookmarkDo
	Omit(cols ...field.Expr) IArticleBookmarkDo
	Join(table schema.Tabler, on ...field.Expr) IArticleBookmarkDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IArticleBookmarkDo
	RightJoin(table schema.Tabler, on ...field.Expr) IArticleBookmarkDo
	Group(cols ...field.Expr) IArticleBookmarkDo
	Having(conds ...gen.Condition) IArticleBookmarkDo
	Limit(limit int) IArticleBookmarkDo
	Offset(offset int) IArticleBookmarkDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IArticleBookmarkDo
	Unscoped() IArticleBookmarkDo
	Create(values ...*model_def.ArticleBookmark) error
	CreateInBatches(values []*model_def.ArticleBookmark, batchSize int) error
	Save(values ...*model_def.ArticleBookmark) error
	First() (*model_def.ArticleBookmark, error)
	Take() (*model_def.ArticleBookmark, error)
	Last() (*model_def.ArticleBookmark, error)
	Find() ([]*model_def.ArticleBookmark, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model_def.ArticleBookmark, err error)
	FindInBatches(result *[]*model_def.ArticleBookmark, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model_def.ArticleBookmark) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IArticleBookmarkDo
	Assign(attrs ...field.AssignExpr) IArticleBookmarkDo
	Joins(fields ...field.RelationField) IArticleBookmarkDo
	Preload(fields ...field.RelationField) IArticleBookmarkDo
	FirstOrInit() (*model_def.ArticleBookmark, error)
	FirstOrCreate() (*model_def.ArticleBookmark, error)
	FindByPage(offset int, limit int) (result []*model_def.ArticleBookmark, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IArticleBookmarkDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a articleBookmarkDo) Debug() IArticleBookmarkDo {
	return a.withDO(a.DO.Debug())
}

func (a articleBookmarkDo) WithContext(ctx context.Context) IArticleBookmarkDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a articleBookmarkDo) ReadDB() IArticleBookmarkDo {
	return a.Clauses(dbresolver.Read)
}

func (a articleBookmarkDo) WriteDB() IArticleBookmarkDo {
	return a.Clauses(dbresolver.Write)
}

func (a articleBookmarkDo) Session(config *gorm.Session) IArticleBookmarkDo {
	return a.withDO(a.DO.Session(config))
}

func (a articleBookmarkDo) Clauses(conds ...clause.Expression) IArticleBookmarkDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a articleBookmarkDo) Returning(value interface{}, columns ...string) IArticleBookmarkDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a articleBookmarkDo) Not(conds ...gen.Condition) IArticleBookmarkDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a articleBookmarkDo) Or(conds ...gen.Condition) IArticleBookmarkDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a articleBookmarkDo) Select(conds ...field.Expr) IArticleBookmarkDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a articleBookmarkDo) Where(conds ...gen.Condition) IArticleBookmarkDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a articleBookmarkDo) Order(conds ...field.Expr) IArticleBookmarkDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a articleBookmarkDo) Distinct(cols ...field.Expr) IArticleBookmarkDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a articleBookmarkDo) Omit(cols ...field.Expr) IArticleBookmarkDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a articleBookmarkDo) Join(table schema.Tabler, on ...field.Expr) IArticleBookmarkDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a articleBookmarkDo) LeftJoin(table schema.Tabler, on ...field.Expr) IArticleBookmarkDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a articleBookmarkDo) RightJoin(table schema.Tabler, on ...field.Expr) IArticleBookmarkDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a articleBookmarkDo) Group(cols ...field.Expr) IArticleBookmarkDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a articleBookmarkDo) Having(conds ...gen.Condition) IArticleBookmarkDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a articleBookmarkDo) Limit(limit int) IArticleBookmarkDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a articleBookmarkDo) Offset(offset int) IArticleBookmarkDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a articleBookmarkDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IArticleBookmarkDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a articleBookmarkDo) Unscoped() IArticleBookmarkDo {
	return a.withDO(a.DO.Unscoped())
}

func (a articleBookmarkDo) Create(values ...*model_def.ArticleBookmark) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a articleBookmarkDo) CreateInBatches(values []*model_def.ArticleBookmark, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a articleBookmarkDo) Save(values ...*model_def.ArticleBookmark) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a articleBookmarkDo) First() (*model_def.ArticleBookmark, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model_def.ArticleBookmark), nil
	}
}

func (a articleBookmarkDo) Take() (*model_def.ArticleBookmark, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model_def.ArticleBookmark), nil
	}
}

func (a articleBookmarkDo) Last() (*model_def.ArticleBookmark, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model_def.ArticleBookmark), nil
	}
}

func (a articleBookmarkDo) Find() ([]*model_def.ArticleBookmark, error) {
	result, err := a.DO.Find()
	return result.([]*model_def.ArticleBookmark), err
}

func (a articleBookmarkDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model_def.ArticleBookmark, err error) {
	buf := make([]*model_def.ArticleBookmark, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a articleBookmarkDo) FindInBatches(result *[]*model_def.ArticleBookmark, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a articleBookmarkDo) Attrs(attrs ...field.AssignExpr) IArticleBookmarkDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a articleBookmarkDo) Assign(attrs ...field.AssignExpr) IArticleBookmarkDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a articleBookmarkDo) Joins(fields ...field.RelationField) IArticleBookmarkDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a articleBookmarkDo) Preload(fields ...field.RelationField) IArticleBookmarkDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a articleBookmarkDo) FirstOrInit() (*model_def.ArticleBookmark, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model_def.ArticleBookmark), nil
	}
}

func (a articleBookmarkDo) FirstOrCreate() (*model_def.ArticleBookmark, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model_def.ArticleBookmark), nil
	}
}

func (a articleBookmarkDo) FindByPage(offset int, limit int) (result []*model_def.ArticleBookmark, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a articleBookmarkDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a articleBookmarkDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a articleBookmarkDo) Delete(models ...*model_def.ArticleBookmark) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *articleBookmarkDo) withDO(do gen.Dao) *articleBookmarkDo {
	a.DO = *do.(*gen.DO)
	return a
}
