// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"blog/model_def"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newArticleVersion(db *gorm.DB, opts ...gen.DOOption) articleVersion {
	_articleVersion := articleVersion{}

	_articleVersion.articleVersionDo.UseDB(db, opts...)
	_articleVersion.articleVersionDo.UseModel(&model_def.ArticleVersion{})

	tableName := _articleVersion.articleVersionDo.TableName()
	_articleVersion.ALL = field.NewAsterisk(tableName)
	_articleVersion.ID = field.NewUint(tableName, "id")
	_articleVersion.CreatedAt = field.NewTime(tableName, "created_at")
	_articleVersion.UpdatedAt = field.NewTime(tableName, "updated_at")
	_articleVersion.ArticleID = field.NewInt32(tableName, "article_id")
	_articleVersion.Description = field.NewString(tableName, "description")
	_articleVersion.Version = field.NewInt(tableName, "version")
	_articleVersion.StoreID = field.NewInt32(tableName, "store_id")

	_articleVersion.fillFieldMap()

	return _articleVersion
}

type articleVersion struct {
	articleVersionDo articleVersionDo

	ALL         field.Asterisk
	ID          field.Uint
	CreatedAt   field.Time
	UpdatedAt   field.Time
	ArticleID   field.Int32
	Description field.String
	Version     field.Int
	StoreID     field.Int32

	fieldMap map[string]field.Expr
}

func (a articleVersion) Table(newTableName string) *articleVersion {
	a.articleVersionDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a articleVersion) As(alias string) *articleVersion {
	a.articleVersionDo.DO = *(a.articleVersionDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *articleVersion) updateTableName(table string) *articleVersion {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.ArticleID = field.NewInt32(table, "article_id")
	a.Description = field.NewString(table, "description")
	a.Version = field.NewInt(table, "version")
	a.StoreID = field.NewInt32(table, "store_id")

	a.fillFieldMap()

	return a
}

func (a *articleVersion) WithContext(ctx context.Context) IArticleVersionDo {
	return a.articleVersionDo.WithContext(ctx)
}

func (a articleVersion) TableName() string { return a.articleVersionDo.TableName() }

func (a articleVersion) Alias() string { return a.articleVersionDo.Alias() }

func (a articleVersion) Columns(cols ...field.Expr) gen.Columns {
	return a.articleVersionDo.Columns(cols...)
}

func (a *articleVersion) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *articleVersion) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 7)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["article_id"] = a.ArticleID
	a.fieldMap["description"] = a.Description
	a.fieldMap["version"] = a.Version
	a.fieldMap["store_id"] = a.StoreID
}

func (a articleVersion) clone(db *gorm.DB) articleVersion {
	a.articleVersionDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a articleVersion) replaceDB(db *gorm.DB) articleVersion {
	a.articleVersionDo.ReplaceDB(db)
	return a
}

type articleVersionDo struct{ gen.DO }

type IArticleVersionDo interface {
	gen.SubQuery
	Debug() IArticleVersionDo
	WithContext(ctx context.Context) IArticleVersionDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IArticleVersionDo
	WriteDB() IArticleVersionDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IArticleVersionDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IArticleVersionDo
	Not(conds ...gen.Condition) IArticleVersionDo
	Or(conds ...gen.Condition) IArticleVersionDo
	Select(conds ...field.Expr) IArticleVersionDo
	Where(conds ...gen.Condition) IArticleVersionDo
	Order(conds ...field.Expr) IArticleVersionDo
	Distinct(cols ...field.Expr) IArticleVersionDo
	Omit(cols ...field.Expr) IArticleVersionDo
	Join(table schema.Tabler, on ...field.Expr) IArticleVersionDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IArticleVersionDo
	RightJoin(table schema.Tabler, on ...field.Expr) IArticleVersionDo
	Group(cols ...field.Expr) IArticleVersionDo
	Having(conds ...gen.Condition) IArticleVersionDo
	Limit(limit int) IArticleVersionDo
	Offset(offset int) IArticleVersionDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IArticleVersionDo
	Unscoped() IArticleVersionDo
	Create(values ...*model_def.ArticleVersion) error
	CreateInBatches(values []*model_def.ArticleVersion, batchSize int) error
	Save(values ...*model_def.ArticleVersion) error
	First() (*model_def.ArticleVersion, error)
	Take() (*model_def.ArticleVersion, error)
	Last() (*model_def.ArticleVersion, error)
	Find() ([]*model_def.ArticleVersion, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model_def.ArticleVersion, err error)
	FindInBatches(result *[]*model_def.ArticleVersion, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model_def.ArticleVersion) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IArticleVersionDo
	Assign(attrs ...field.AssignExpr) IArticleVersionDo
	Joins(fields ...field.RelationField) IArticleVersionDo
	Preload(fields ...field.RelationField) IArticleVersionDo
	FirstOrInit() (*model_def.ArticleVersion, error)
	FirstOrCreate() (*model_def.ArticleVersion, error)
	FindByPage(offset int, limit int) (result []*model_def.ArticleVersion, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IArticleVersionDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a articleVersionDo) Debug() IArticleVersionDo {
	return a.withDO(a.DO.Debug())
}

func (a articleVersionDo) WithContext(ctx context.Context) IArticleVersionDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a articleVersionDo) ReadDB() IArticleVersionDo {
	return a.Clauses(dbresolver.Read)
}

func (a articleVersionDo) WriteDB() IArticleVersionDo {
	return a.Clauses(dbresolver.Write)
}

func (a articleVersionDo) Session(config *gorm.Session) IArticleVersionDo {
	return a.withDO(a.DO.Session(config))
}

func (a articleVersionDo) Clauses(conds ...clause.Expression) IArticleVersionDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a articleVersionDo) Returning(value interface{}, columns ...string) IArticleVersionDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a articleVersionDo) Not(conds ...gen.Condition) IArticleVersionDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a articleVersionDo) Or(conds ...gen.Condition) IArticleVersionDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a articleVersionDo) Select(conds ...field.Expr) IArticleVersionDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a articleVersionDo) Where(conds ...gen.Condition) IArticleVersionDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a articleVersionDo) Order(conds ...field.Expr) IArticleVersionDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a articleVersionDo) Distinct(cols ...field.Expr) IArticleVersionDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a articleVersionDo) Omit(cols ...field.Expr) IArticleVersionDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a articleVersionDo) Join(table schema.Tabler, on ...field.Expr) IArticleVersionDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a articleVersionDo) LeftJoin(table schema.Tabler, on ...field.Expr) IArticleVersionDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a articleVersionDo) RightJoin(table schema.Tabler, on ...field.Expr) IArticleVersionDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a articleVersionDo) Group(cols ...field.Expr) IArticleVersionDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a articleVersionDo) Having(conds ...gen.Condition) IArticleVersionDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a articleVersionDo) Limit(limit int) IArticleVersionDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a articleVersionDo) Offset(offset int) IArticleVersionDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a articleVersionDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IArticleVersionDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a articleVersionDo) Unscoped() IArticleVersionDo {
	return a.withDO(a.DO.Unscoped())
}

func (a articleVersionDo) Create(values ...*model_def.ArticleVersion) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a articleVersionDo) CreateInBatches(values []*model_def.ArticleVersion, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a articleVersionDo) Save(values ...*model_def.ArticleVersion) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a articleVersionDo) First() (*model_def.ArticleVersion, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model_def.ArticleVersion), nil
	}
}

func (a articleVersionDo) Take() (*model_def.ArticleVersion, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model_def.ArticleVersion), nil
	}
}

func (a articleVersionDo) Last() (*model_def.ArticleVersion, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model_def.ArticleVersion), nil
	}
}

func (a articleVersionDo) Find() ([]*model_def.ArticleVersion, error) {
	result, err := a.DO.Find()
	return result.([]*model_def.ArticleVersion), err
}

func (a articleVersionDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model_def.ArticleVersion, err error) {
	buf := make([]*model_def.ArticleVersion, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a articleVersionDo) FindInBatches(result *[]*model_def.ArticleVersion, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a articleVersionDo) Attrs(attrs ...field.AssignExpr) IArticleVersionDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a articleVersionDo) Assign(attrs ...field.AssignExpr) IArticleVersionDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a articleVersionDo) Joins(fields ...field.RelationField) IArticleVersionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a articleVersionDo) Preload(fields ...field.RelationField) IArticleVersionDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a articleVersionDo) FirstOrInit() (*model_def.ArticleVersion, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model_def.ArticleVersion), nil
	}
}

func (a articleVersionDo) FirstOrCreate() (*model_def.ArticleVersion, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model_def.ArticleVersion), nil
	}
}

func (a articleVersionDo) FindByPage(offset int, limit int) (result []*model_def.ArticleVersion, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a articleVersionDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a articleVersionDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a articleVersionDo) Delete(models ...*model_def.ArticleVersion) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *articleVersionDo) withDO(do gen.Dao) *articleVersionDo {
	a.DO = *do.(*gen.DO)
	return a
}
