// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"blog/model_def"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newArticleLike(db *gorm.DB, opts ...gen.DOOption) articleLike {
	_articleLike := articleLike{}

	_articleLike.articleLikeDo.UseDB(db, opts...)
	_articleLike.articleLikeDo.UseModel(&model_def.ArticleLike{})

	tableName := _articleLike.articleLikeDo.TableName()
	_articleLike.ALL = field.NewAsterisk(tableName)
	_articleLike.ID = field.NewUint(tableName, "id")
	_articleLike.CreatedAt = field.NewTime(tableName, "created_at")
	_articleLike.UpdatedAt = field.NewTime(tableName, "updated_at")
	_articleLike.DeletedAt = field.NewField(tableName, "deleted_at")
	_articleLike.UserID = field.NewInt32(tableName, "user_id")
	_articleLike.ArticleID = field.NewInt32(tableName, "article_id")

	_articleLike.fillFieldMap()

	return _articleLike
}

type articleLike struct {
	articleLikeDo articleLikeDo

	ALL       field.Asterisk
	ID        field.Uint
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	UserID    field.Int32
	ArticleID field.Int32

	fieldMap map[string]field.Expr
}

func (a articleLike) Table(newTableName string) *articleLike {
	a.articleLikeDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a articleLike) As(alias string) *articleLike {
	a.articleLikeDo.DO = *(a.articleLikeDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *articleLike) updateTableName(table string) *articleLike {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewUint(table, "id")
	a.CreatedAt = field.NewTime(table, "created_at")
	a.UpdatedAt = field.NewTime(table, "updated_at")
	a.DeletedAt = field.NewField(table, "deleted_at")
	a.UserID = field.NewInt32(table, "user_id")
	a.ArticleID = field.NewInt32(table, "article_id")

	a.fillFieldMap()

	return a
}

func (a *articleLike) WithContext(ctx context.Context) IArticleLikeDo {
	return a.articleLikeDo.WithContext(ctx)
}

func (a articleLike) TableName() string { return a.articleLikeDo.TableName() }

func (a articleLike) Alias() string { return a.articleLikeDo.Alias() }

func (a articleLike) Columns(cols ...field.Expr) gen.Columns { return a.articleLikeDo.Columns(cols...) }

func (a *articleLike) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *articleLike) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 6)
	a.fieldMap["id"] = a.ID
	a.fieldMap["created_at"] = a.CreatedAt
	a.fieldMap["updated_at"] = a.UpdatedAt
	a.fieldMap["deleted_at"] = a.DeletedAt
	a.fieldMap["user_id"] = a.UserID
	a.fieldMap["article_id"] = a.ArticleID
}

func (a articleLike) clone(db *gorm.DB) articleLike {
	a.articleLikeDo.ReplaceConnPool(db.Statement.ConnPool)
	return a
}

func (a articleLike) replaceDB(db *gorm.DB) articleLike {
	a.articleLikeDo.ReplaceDB(db)
	return a
}

type articleLikeDo struct{ gen.DO }

type IArticleLikeDo interface {
	gen.SubQuery
	Debug() IArticleLikeDo
	WithContext(ctx context.Context) IArticleLikeDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IArticleLikeDo
	WriteDB() IArticleLikeDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IArticleLikeDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IArticleLikeDo
	Not(conds ...gen.Condition) IArticleLikeDo
	Or(conds ...gen.Condition) IArticleLikeDo
	Select(conds ...field.Expr) IArticleLikeDo
	Where(conds ...gen.Condition) IArticleLikeDo
	Order(conds ...field.Expr) IArticleLikeDo
	Distinct(cols ...field.Expr) IArticleLikeDo
	Omit(cols ...field.Expr) IArticleLikeDo
	Join(table schema.Tabler, on ...field.Expr) IArticleLikeDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IArticleLikeDo
	RightJoin(table schema.Tabler, on ...field.Expr) IArticleLikeDo
	Group(cols ...field.Expr) IArticleLikeDo
	Having(conds ...gen.Condition) IArticleLikeDo
	Limit(limit int) IArticleLikeDo
	Offset(offset int) IArticleLikeDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IArticleLikeDo
	Unscoped() IArticleLikeDo
	Create(values ...*model_def.ArticleLike) error
	CreateInBatches(values []*model_def.ArticleLike, batchSize int) error
	Save(values ...*model_def.ArticleLike) error
	First() (*model_def.ArticleLike, error)
	Take() (*model_def.ArticleLike, error)
	Last() (*model_def.ArticleLike, error)
	Find() ([]*model_def.ArticleLike, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model_def.ArticleLike, err error)
	FindInBatches(result *[]*model_def.ArticleLike, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model_def.ArticleLike) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IArticleLikeDo
	Assign(attrs ...field.AssignExpr) IArticleLikeDo
	Joins(fields ...field.RelationField) IArticleLikeDo
	Preload(fields ...field.RelationField) IArticleLikeDo
	FirstOrInit() (*model_def.ArticleLike, error)
	FirstOrCreate() (*model_def.ArticleLike, error)
	FindByPage(offset int, limit int) (result []*model_def.ArticleLike, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IArticleLikeDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (a articleLikeDo) Debug() IArticleLikeDo {
	return a.withDO(a.DO.Debug())
}

func (a articleLikeDo) WithContext(ctx context.Context) IArticleLikeDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a articleLikeDo) ReadDB() IArticleLikeDo {
	return a.Clauses(dbresolver.Read)
}

func (a articleLikeDo) WriteDB() IArticleLikeDo {
	return a.Clauses(dbresolver.Write)
}

func (a articleLikeDo) Session(config *gorm.Session) IArticleLikeDo {
	return a.withDO(a.DO.Session(config))
}

func (a articleLikeDo) Clauses(conds ...clause.Expression) IArticleLikeDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a articleLikeDo) Returning(value interface{}, columns ...string) IArticleLikeDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a articleLikeDo) Not(conds ...gen.Condition) IArticleLikeDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a articleLikeDo) Or(conds ...gen.Condition) IArticleLikeDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a articleLikeDo) Select(conds ...field.Expr) IArticleLikeDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a articleLikeDo) Where(conds ...gen.Condition) IArticleLikeDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a articleLikeDo) Order(conds ...field.Expr) IArticleLikeDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a articleLikeDo) Distinct(cols ...field.Expr) IArticleLikeDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a articleLikeDo) Omit(cols ...field.Expr) IArticleLikeDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a articleLikeDo) Join(table schema.Tabler, on ...field.Expr) IArticleLikeDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a articleLikeDo) LeftJoin(table schema.Tabler, on ...field.Expr) IArticleLikeDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a articleLikeDo) RightJoin(table schema.Tabler, on ...field.Expr) IArticleLikeDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a articleLikeDo) Group(cols ...field.Expr) IArticleLikeDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a articleLikeDo) Having(conds ...gen.Condition) IArticleLikeDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a articleLikeDo) Limit(limit int) IArticleLikeDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a articleLikeDo) Offset(offset int) IArticleLikeDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a articleLikeDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IArticleLikeDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a articleLikeDo) Unscoped() IArticleLikeDo {
	return a.withDO(a.DO.Unscoped())
}

func (a articleLikeDo) Create(values ...*model_def.ArticleLike) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a articleLikeDo) CreateInBatches(values []*model_def.ArticleLike, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a articleLikeDo) Save(values ...*model_def.ArticleLike) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a articleLikeDo) First() (*model_def.ArticleLike, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model_def.ArticleLike), nil
	}
}

func (a articleLikeDo) Take() (*model_def.ArticleLike, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model_def.ArticleLike), nil
	}
}

func (a articleLikeDo) Last() (*model_def.ArticleLike, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model_def.ArticleLike), nil
	}
}

func (a articleLikeDo) Find() ([]*model_def.ArticleLike, error) {
	result, err := a.DO.Find()
	return result.([]*model_def.ArticleLike), err
}

func (a articleLikeDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model_def.ArticleLike, err error) {
	buf := make([]*model_def.ArticleLike, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a articleLikeDo) FindInBatches(result *[]*model_def.ArticleLike, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a articleLikeDo) Attrs(attrs ...field.AssignExpr) IArticleLikeDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a articleLikeDo) Assign(attrs ...field.AssignExpr) IArticleLikeDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a articleLikeDo) Joins(fields ...field.RelationField) IArticleLikeDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a articleLikeDo) Preload(fields ...field.RelationField) IArticleLikeDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a articleLikeDo) FirstOrInit() (*model_def.ArticleLike, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model_def.ArticleLike), nil
	}
}

func (a articleLikeDo) FirstOrCreate() (*model_def.ArticleLike, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model_def.ArticleLike), nil
	}
}

func (a articleLikeDo) FindByPage(offset int, limit int) (result []*model_def.ArticleLike, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a articleLikeDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a articleLikeDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a articleLikeDo) Delete(models ...*model_def.ArticleLike) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *articleLikeDo) withDO(do gen.Dao) *articleLikeDo {
	a.DO = *do.(*gen.DO)
	return a
}
