// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"blog/model_def"
	"context"
	"database/sql"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"
)

func newWebInfo(db *gorm.DB, opts ...gen.DOOption) webInfo {
	_webInfo := webInfo{}

	_webInfo.webInfoDo.UseDB(db, opts...)
	_webInfo.webInfoDo.UseModel(&model_def.WebInfo{})

	tableName := _webInfo.webInfoDo.TableName()
	_webInfo.ALL = field.NewAsterisk(tableName)
	_webInfo.ID = field.NewUint(tableName, "id")
	_webInfo.ArticleNum = field.NewInt(tableName, "article_num")
	_webInfo.FileNum = field.NewInt(tableName, "file_num")
	_webInfo.UserNum = field.NewInt(tableName, "user_num")
	_webInfo.CategoriesNum = field.NewInt(tableName, "categories")
	_webInfo.CommentsNum = field.NewInt(tableName, "comments")
	_webInfo.StoreUsage = field.NewString(tableName, "store_usage")
	_webInfo.Capacity = field.NewString(tableName, "capacity")
	_webInfo.Views = field.NewInt(tableName, "views")
	_webInfo.LastUpdate = field.NewTime(tableName, "last_update")
	_webInfo.LastLogin = field.NewTime(tableName, "last_login")
	_webInfo.LastClear = field.NewTime(tableName, "last_clear")
	_webInfo.LastBackup = field.NewTime(tableName, "last_backup")

	_webInfo.fillFieldMap()

	return _webInfo
}

type webInfo struct {
	webInfoDo webInfoDo

	ALL           field.Asterisk
	ID            field.Uint
	ArticleNum    field.Int
	FileNum       field.Int
	UserNum       field.Int
	CategoriesNum field.Int
	CommentsNum   field.Int
	StoreUsage    field.String
	Capacity      field.String
	Views         field.Int
	LastUpdate    field.Time
	LastLogin     field.Time
	LastClear     field.Time
	LastBackup    field.Time

	fieldMap map[string]field.Expr
}

func (w webInfo) Table(newTableName string) *webInfo {
	w.webInfoDo.UseTable(newTableName)
	return w.updateTableName(newTableName)
}

func (w webInfo) As(alias string) *webInfo {
	w.webInfoDo.DO = *(w.webInfoDo.As(alias).(*gen.DO))
	return w.updateTableName(alias)
}

func (w *webInfo) updateTableName(table string) *webInfo {
	w.ALL = field.NewAsterisk(table)
	w.ID = field.NewUint(table, "id")
	w.ArticleNum = field.NewInt(table, "article_num")
	w.FileNum = field.NewInt(table, "file_num")
	w.UserNum = field.NewInt(table, "user_num")
	w.CategoriesNum = field.NewInt(table, "categories")
	w.CommentsNum = field.NewInt(table, "comments")
	w.StoreUsage = field.NewString(table, "store_usage")
	w.Capacity = field.NewString(table, "capacity")
	w.Views = field.NewInt(table, "views")
	w.LastUpdate = field.NewTime(table, "last_update")
	w.LastLogin = field.NewTime(table, "last_login")
	w.LastClear = field.NewTime(table, "last_clear")
	w.LastBackup = field.NewTime(table, "last_backup")

	w.fillFieldMap()

	return w
}

func (w *webInfo) WithContext(ctx context.Context) IWebInfoDo { return w.webInfoDo.WithContext(ctx) }

func (w webInfo) TableName() string { return w.webInfoDo.TableName() }

func (w webInfo) Alias() string { return w.webInfoDo.Alias() }

func (w webInfo) Columns(cols ...field.Expr) gen.Columns { return w.webInfoDo.Columns(cols...) }

func (w *webInfo) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := w.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (w *webInfo) fillFieldMap() {
	w.fieldMap = make(map[string]field.Expr, 13)
	w.fieldMap["id"] = w.ID
	w.fieldMap["article_num"] = w.ArticleNum
	w.fieldMap["file_num"] = w.FileNum
	w.fieldMap["user_num"] = w.UserNum
	w.fieldMap["categories"] = w.CategoriesNum
	w.fieldMap["comments"] = w.CommentsNum
	w.fieldMap["store_usage"] = w.StoreUsage
	w.fieldMap["capacity"] = w.Capacity
	w.fieldMap["views"] = w.Views
	w.fieldMap["last_update"] = w.LastUpdate
	w.fieldMap["last_login"] = w.LastLogin
	w.fieldMap["last_clear"] = w.LastClear
	w.fieldMap["last_backup"] = w.LastBackup
}

func (w webInfo) clone(db *gorm.DB) webInfo {
	w.webInfoDo.ReplaceConnPool(db.Statement.ConnPool)
	return w
}

func (w webInfo) replaceDB(db *gorm.DB) webInfo {
	w.webInfoDo.ReplaceDB(db)
	return w
}

type webInfoDo struct{ gen.DO }

type IWebInfoDo interface {
	gen.SubQuery
	Debug() IWebInfoDo
	WithContext(ctx context.Context) IWebInfoDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IWebInfoDo
	WriteDB() IWebInfoDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IWebInfoDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IWebInfoDo
	Not(conds ...gen.Condition) IWebInfoDo
	Or(conds ...gen.Condition) IWebInfoDo
	Select(conds ...field.Expr) IWebInfoDo
	Where(conds ...gen.Condition) IWebInfoDo
	Order(conds ...field.Expr) IWebInfoDo
	Distinct(cols ...field.Expr) IWebInfoDo
	Omit(cols ...field.Expr) IWebInfoDo
	Join(table schema.Tabler, on ...field.Expr) IWebInfoDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IWebInfoDo
	RightJoin(table schema.Tabler, on ...field.Expr) IWebInfoDo
	Group(cols ...field.Expr) IWebInfoDo
	Having(conds ...gen.Condition) IWebInfoDo
	Limit(limit int) IWebInfoDo
	Offset(offset int) IWebInfoDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IWebInfoDo
	Unscoped() IWebInfoDo
	Create(values ...*model_def.WebInfo) error
	CreateInBatches(values []*model_def.WebInfo, batchSize int) error
	Save(values ...*model_def.WebInfo) error
	First() (*model_def.WebInfo, error)
	Take() (*model_def.WebInfo, error)
	Last() (*model_def.WebInfo, error)
	Find() ([]*model_def.WebInfo, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model_def.WebInfo, err error)
	FindInBatches(result *[]*model_def.WebInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model_def.WebInfo) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IWebInfoDo
	Assign(attrs ...field.AssignExpr) IWebInfoDo
	Joins(fields ...field.RelationField) IWebInfoDo
	Preload(fields ...field.RelationField) IWebInfoDo
	FirstOrInit() (*model_def.WebInfo, error)
	FirstOrCreate() (*model_def.WebInfo, error)
	FindByPage(offset int, limit int) (result []*model_def.WebInfo, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Rows() (*sql.Rows, error)
	Row() *sql.Row
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IWebInfoDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (w webInfoDo) Debug() IWebInfoDo {
	return w.withDO(w.DO.Debug())
}

func (w webInfoDo) WithContext(ctx context.Context) IWebInfoDo {
	return w.withDO(w.DO.WithContext(ctx))
}

func (w webInfoDo) ReadDB() IWebInfoDo {
	return w.Clauses(dbresolver.Read)
}

func (w webInfoDo) WriteDB() IWebInfoDo {
	return w.Clauses(dbresolver.Write)
}

func (w webInfoDo) Session(config *gorm.Session) IWebInfoDo {
	return w.withDO(w.DO.Session(config))
}

func (w webInfoDo) Clauses(conds ...clause.Expression) IWebInfoDo {
	return w.withDO(w.DO.Clauses(conds...))
}

func (w webInfoDo) Returning(value interface{}, columns ...string) IWebInfoDo {
	return w.withDO(w.DO.Returning(value, columns...))
}

func (w webInfoDo) Not(conds ...gen.Condition) IWebInfoDo {
	return w.withDO(w.DO.Not(conds...))
}

func (w webInfoDo) Or(conds ...gen.Condition) IWebInfoDo {
	return w.withDO(w.DO.Or(conds...))
}

func (w webInfoDo) Select(conds ...field.Expr) IWebInfoDo {
	return w.withDO(w.DO.Select(conds...))
}

func (w webInfoDo) Where(conds ...gen.Condition) IWebInfoDo {
	return w.withDO(w.DO.Where(conds...))
}

func (w webInfoDo) Order(conds ...field.Expr) IWebInfoDo {
	return w.withDO(w.DO.Order(conds...))
}

func (w webInfoDo) Distinct(cols ...field.Expr) IWebInfoDo {
	return w.withDO(w.DO.Distinct(cols...))
}

func (w webInfoDo) Omit(cols ...field.Expr) IWebInfoDo {
	return w.withDO(w.DO.Omit(cols...))
}

func (w webInfoDo) Join(table schema.Tabler, on ...field.Expr) IWebInfoDo {
	return w.withDO(w.DO.Join(table, on...))
}

func (w webInfoDo) LeftJoin(table schema.Tabler, on ...field.Expr) IWebInfoDo {
	return w.withDO(w.DO.LeftJoin(table, on...))
}

func (w webInfoDo) RightJoin(table schema.Tabler, on ...field.Expr) IWebInfoDo {
	return w.withDO(w.DO.RightJoin(table, on...))
}

func (w webInfoDo) Group(cols ...field.Expr) IWebInfoDo {
	return w.withDO(w.DO.Group(cols...))
}

func (w webInfoDo) Having(conds ...gen.Condition) IWebInfoDo {
	return w.withDO(w.DO.Having(conds...))
}

func (w webInfoDo) Limit(limit int) IWebInfoDo {
	return w.withDO(w.DO.Limit(limit))
}

func (w webInfoDo) Offset(offset int) IWebInfoDo {
	return w.withDO(w.DO.Offset(offset))
}

func (w webInfoDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IWebInfoDo {
	return w.withDO(w.DO.Scopes(funcs...))
}

func (w webInfoDo) Unscoped() IWebInfoDo {
	return w.withDO(w.DO.Unscoped())
}

func (w webInfoDo) Create(values ...*model_def.WebInfo) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Create(values)
}

func (w webInfoDo) CreateInBatches(values []*model_def.WebInfo, batchSize int) error {
	return w.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (w webInfoDo) Save(values ...*model_def.WebInfo) error {
	if len(values) == 0 {
		return nil
	}
	return w.DO.Save(values)
}

func (w webInfoDo) First() (*model_def.WebInfo, error) {
	if result, err := w.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model_def.WebInfo), nil
	}
}

func (w webInfoDo) Take() (*model_def.WebInfo, error) {
	if result, err := w.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model_def.WebInfo), nil
	}
}

func (w webInfoDo) Last() (*model_def.WebInfo, error) {
	if result, err := w.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model_def.WebInfo), nil
	}
}

func (w webInfoDo) Find() ([]*model_def.WebInfo, error) {
	result, err := w.DO.Find()
	return result.([]*model_def.WebInfo), err
}

func (w webInfoDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model_def.WebInfo, err error) {
	buf := make([]*model_def.WebInfo, 0, batchSize)
	err = w.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (w webInfoDo) FindInBatches(result *[]*model_def.WebInfo, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return w.DO.FindInBatches(result, batchSize, fc)
}

func (w webInfoDo) Attrs(attrs ...field.AssignExpr) IWebInfoDo {
	return w.withDO(w.DO.Attrs(attrs...))
}

func (w webInfoDo) Assign(attrs ...field.AssignExpr) IWebInfoDo {
	return w.withDO(w.DO.Assign(attrs...))
}

func (w webInfoDo) Joins(fields ...field.RelationField) IWebInfoDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Joins(_f))
	}
	return &w
}

func (w webInfoDo) Preload(fields ...field.RelationField) IWebInfoDo {
	for _, _f := range fields {
		w = *w.withDO(w.DO.Preload(_f))
	}
	return &w
}

func (w webInfoDo) FirstOrInit() (*model_def.WebInfo, error) {
	if result, err := w.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model_def.WebInfo), nil
	}
}

func (w webInfoDo) FirstOrCreate() (*model_def.WebInfo, error) {
	if result, err := w.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model_def.WebInfo), nil
	}
}

func (w webInfoDo) FindByPage(offset int, limit int) (result []*model_def.WebInfo, count int64, err error) {
	result, err = w.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = w.Offset(-1).Limit(-1).Count()
	return
}

func (w webInfoDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = w.Count()
	if err != nil {
		return
	}

	err = w.Offset(offset).Limit(limit).Scan(result)
	return
}

func (w webInfoDo) Scan(result interface{}) (err error) {
	return w.DO.Scan(result)
}

func (w webInfoDo) Delete(models ...*model_def.WebInfo) (result gen.ResultInfo, err error) {
	return w.DO.Delete(models)
}

func (w *webInfoDo) withDO(do gen.Dao) *webInfoDo {
	w.DO = *do.(*gen.DO)
	return w
}
